RelationalDatabase:
  Type: MySQL
  Addr: localhost:3306
  Username: root
  DatabaseName: django-start-kit
  Password: panhq112358
  PathParam: {"foo":["bar", ]}, {"key": ["value", ]}
  GORM:
    MaxIdleConnections:
    MaxOpenConnections:

Redis:
  Addr: localhost:6379
  DatabaseName: 0
  Password:

System:
  Addr: 0.0.0.0:8000
  Environment: Development
  Debug: true
  RequestSchema: https
  Label: GinStartKit
  Description: GinStartKit
  WhiteList: [ ]
  BlackList: [ ]
  Cors:
    AllowAll: true
    AllowOrigins: [ ]
    AllowMethods: [ ]
    AllowHeaders: [ ]
    ExposeHeaders: [ ]
    AllowCredentials: true
    MaxAge: 3600


Log:
  Level: debug

Hbase:
  AddrList: [ "192.168.3.75:9090" ]

Kafka:
  AddrList: [ ]

Jwt:
  Secret: secret
  AuthHeaderPrefix: Jwt
  ExpireMinute: 432000
  RefreshMinute: 4320
  Issuer: phoenix