basePath: /api/v1/
definitions:
  Response-model_UserLoginWithPhone:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.UserLoginWithPhone'
      message:
        type: string
      time:
        type: string
    type: object
  Response-model_UserLoginWithUsername:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/model.UserLoginWithUsername'
      message:
        type: string
      time:
        type: string
    type: object
  ResponseWithPageInfo-array_account_UserResponseModel:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/account.UserResponseModel'
        type: array
      message:
        type: string
      pageInfo:
        $ref: '#/definitions/response.PageInfo'
      time:
        type: string
    type: object
  account.UserResponseModel:
    properties:
      avatar:
        description: 用户头像
        maxLength: 256
        type: string
      email:
        description: 用户邮箱
        type: string
      enabled:
        description: 用户是否被禁用 1启用 0禁用
        type: boolean
      id:
        type: integer
      nickname:
        description: 用户昵称
        maxLength: 64
        type: string
      phone:
        description: 用户手机号
        type: string
      systems:
        items:
          $ref: '#/definitions/model.SystemSimpleFields'
        type: array
      username:
        description: 用户登录名
        maxLength: 32
        minLength: 6
        type: string
    required:
    - nickname
    - phone
    - username
    type: object
  auth.UserRegisterIn:
    properties:
      avatar:
        description: 用户头像
        maxLength: 256
        type: string
      email:
        description: 用户邮箱
        type: string
      enabled:
        description: 用户是否被禁用 1启用 0禁用
        type: boolean
      nickname:
        description: 用户昵称
        maxLength: 64
        type: string
      password:
        description: 用户登录密码
        maxLength: 20
        minLength: 10
        type: string
      phone:
        description: 用户手机号
        type: string
      systemIds:
        items:
          type: integer
        type: array
      username:
        description: 用户登录名
        maxLength: 32
        minLength: 6
        type: string
    required:
    - nickname
    - phone
    - systemIds
    - username
    type: object
  model.SystemSimpleFields:
    properties:
      code:
        maxLength: 32
        minLength: 1
        type: string
      description:
        maxLength: 255
        type: string
      id:
        type: integer
      label:
        maxLength: 64
        minLength: 1
        type: string
    required:
    - code
    - label
    type: object
  model.UserLoginWithPhone:
    properties:
      password:
        description: 用户登录密码
        maxLength: 20
        minLength: 10
        type: string
      phone:
        description: 用户手机号
        type: string
    required:
    - phone
    type: object
  model.UserLoginWithUsername:
    properties:
      password:
        description: 用户登录密码
        maxLength: 20
        minLength: 10
        type: string
      username:
        description: 用户登录名
        maxLength: 32
        minLength: 6
        type: string
    required:
    - username
    type: object
  response.PageInfo:
    properties:
      pageNum:
        type: integer
      pageSize:
        type: integer
      totalCount:
        type: integer
      totalPage:
        type: integer
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: hypofiasco@gmail.com
    name: hypo-fiasco
    url: https://github.com/hail-pas/GinStartKit
  description: Start Kit of Gin
  license:
    name: MIT
    url: https://github.com/hail-pas/GinStartKit
  termsOfService: https://github.com/hail-pas/GinStartKit
  title: GInStartKit
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/x-www-form-urlencoded
      operationId: get-account-list
      parameters:
      - description: 页码
        in: query
        name: PageNum
        required: true
        type: integer
      - description: 页长
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseWithPageInfo-array_account_UserResponseModel'
      security:
      - Jwt: []
      summary: 用户列表
      tags:
      - Account
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginWithPhone'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-model_UserLoginWithPhone'
      summary: 登录接口
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.UserRegisterIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response-model_UserLoginWithUsername'
      summary: 注册接口
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  Jwt:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
